Project-Online-Doctor-devel/POD/POD/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('sddds/', include('SDDDS.urls')),
    path('admin/', admin.site.urls),
]

Project-Online-Doctor-devel/POD/SDDDS/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = 'sddds'
urlpatterns = [
    path('index_json/', views.index, name='index_json'),
    path('odapi/', views.odapi, name='odapi'),
    
    path('', views.index, name='index'),
    path('process_symptoms/', views.process_symptoms, name='process_symptoms'),
    path('results/<str:doctors>', views.results, name='results'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Project-Online-Doctor-devel/POD/SDDDS/models.py
from django.db import models
from django.conf import settings

# Everything presented here should be improved,
# i.e. the implementation in prolog had an ability to make such constructions 
# like "(SYMPTOM_0 and SYMPTOM_1) or (SYMPTOM_2 and SYMPTOM_3 and not SYMPTOM4)"
# but now we are limited to two sets of symptoms. The same is applicable to the
# Disease model and its relation with Doctor class.

# Constants
B = '  ['  # begin
M = ']  [' # middle
E = ' ]'      # end
SEPARATOR = '; '

class Category(models.Model):
    category_name = models.CharField(max_length=100, verbose_name="Категория симптомов")
    
    def __str__(self):
        return self.category_name

class Symptom(models.Model):
    symptom_text = models.CharField(max_length=500, unique=True, verbose_name="Симптом")
    category = models.ForeignKey(Category, null=True, on_delete=models.CASCADE, verbose_name="Категория")
    
    def __str__(self):
        return self.symptom_text

class Disease(models.Model):
    disease_name = models.CharField(max_length=200, unique=True, verbose_name="Название класса заболеваний")
    allowing_symptoms = models.ManyToManyField(Symptom, blank=True, verbose_name="Возможные симптомы", related_name='a_s')
    prohibiting_symptoms = models.ManyToManyField(Symptom, blank=True, verbose_name="Исключающие симптомы", related_name='p_s')
    
    def __str__(self):
        sa = ' '
        temp_list = list(self.allowing_symptoms.all())
        for i in temp_list:
            sa+= i.symptom_text + SEPARATOR
        sp = ' '
        temp_list = list(self.prohibiting_symptoms.all())
        for i in temp_list:
            sp+= i.symptom_text + SEPARATOR
        return self.disease_name + B + sa[:-2] + M + sp[:-2] + E

class Doctor(models.Model):
    doctor_name = models.CharField(max_length=100, unique=True, verbose_name="Специалист")
    allowing_diseases = models.ManyToManyField(Disease, blank=True, verbose_name="Лечит", related_name='a_d')
    # ~ prohibiting_diseases = models.ManyToManyField(Disease, blank=True, verbose_name="Не лечит", related_name='p_d')
    
    def __str__(self):
        sa = ' '
        temp_list = list(self.allowing_diseases.all())
        for i in temp_list:
            sa+= i.disease_name + SEPARATOR
        # ~ sp = ' '
        # ~ temp_list = list(self.prohibiting_diseases.all())
        # ~ for i in temp_list:
            # ~ sp+= i.disease_name + SEPARATOR
        return self.doctor_name + B + sa[:-2] + E #M + sp[:-2] + 



class HistoryEntry(models.Model):
	user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name="Пользователь")
	symptoms = models.CharField(max_length=1000, verbose_name="Введённые симптомы") 
	result = models.CharField(max_length=1000, verbose_name="Рекомендованные специалисты")

Project-Online-Doctor-devel/POD/SDDDS/views.py
from django.shortcuts import render
from django.http import HttpResponse, JsonResponse, HttpResponseBadRequest, HttpResponseRedirect 
from django.views.decorators.csrf import ensure_csrf_cookie, csrf_exempt
from django.urls import reverse

import json

from . import models

def to_pk_set(qs):
    pk_set = set()
    for i in list(qs):
        pk_set.add(i.pk)
    return pk_set

def sddprocessor(slist, mode): # SET_OF_ITEMS = ALLOWING_SET - PROHIBITING_SET
    
    dlist = []
    present_symptoms = []
    allowing_dis_set = set()
    prohibiting_dis_set = set()
    allowing_doc_set = set()
    prohibiting_doc_set = set()
    
    for i in slist:
        recieved = models.Symptom.objects.filter(symptom_text=i)
        if len(recieved) > 0:
            present_symptoms.append(recieved[0].pk)
    for i in present_symptoms: # code style should be improved
        allowing_dis_set |= to_pk_set(models.Disease.objects.filter(
                allowing_symptoms=i) # getting primary keys
        )
        prohibiting_dis_set |= to_pk_set(models.Disease.objects.filter(
                prohibiting_symptoms=i)
        )
    disease_set = allowing_dis_set - prohibiting_dis_set # substracting
    for i in disease_set:
        allowing_doc_set |= to_pk_set(models.Doctor.objects.filter(
                allowing_diseases=i) # getting PK again
        )
     
        # ~ prohibiting_doc_set |= to_pk_set(models.Doctor.objects.filter(
                # ~ prohibiting_diseases=i)
        # ~ )
    doctor_set = allowing_doc_set #- prohibiting_doc_set # substructing again
    for i in doctor_set:
        dlist.append(models.Doctor.objects.get(pk=i).doctor_name)
    if mode == 'external':
        result = {'dlist' : dlist}
    elif mode == 'internal':
        result = {'dlist' : dlist, 'pk_list' : list(doctor_set)}
    return result



def index(request):
    categories = models.Category.objects.all().order_by('category_name')
    return render(request, 'SDDDS/symptoms.html', {'categories':categories})

def process_symptoms(request):
    if request.method == 'POST': # check if the request is POST
        print(request.POST.dict())
        print(request.POST.getlist('slist'))
        if 'slist' in request.POST:
            result = sddprocessor(request.POST.getlist('slist'), 'internal')
            # TODO: add to db
            json_out = json.dumps(result['dlist'])[2:-2]
            return HttpResponseRedirect(reverse('sddds:results', args=(json_out,)))
    return HttpResponseBadRequest('Not a POST request.') 
    # say the user is too curious

def results(request, doctors):
    doctors = json.loads('["'+doctors+'"]')
    return render(request, 'SDDDS/results.html', {'doctors':doctors})


# Deprecated API
# we'll fallback to it if i screw up in templates
def get_symptoms():
    response = dict()
    cat_list = list(models.Category.objects.all())
    symp_names = []
    for i in cat_list:
        symp_list = list(i.symptom_set.all())
        for j in symp_list:
            symp_names.append(j.symptom_text)
        response[i.category_name] = symp_names[:]
        symp_names.clear()
    return response

def index_json(request):
    jresponse = get_symptoms()
    return JsonResponse(jresponse)
    # returns something like this:
    # {category:[symptoms], category:[symptoms],...}

#@ensure_csrf_cookie
@csrf_exempt # for testing purposes
def odapi(request):
    if request.method == 'POST': # check if the request is POST
        json_in = json.loads(request.readline()) # get the JSON
        json_out = sddprocessor(json_in['slist'], 'external') # process it
        return JsonResponse(json_out) # response with JSON
    return HttpResponseBadRequest('No JSON data.') # or say the user to be moron

Project-Online-Doctor-devel/POD/SDDDS/templates/SDDDS/base.html
<!DOCTYPE html>
<html>
	<head>
		{% load static %}
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<!-- Bootstrap CSS -->
		
		<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
		<link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>
		<link rel="stylesheet" href="{% static 'SDDDS/css/main.css' %}">
		<link rel="stylesheet" href="{% static 'SDDDS/css/test.css' %}">
		<title>{% block title %}Base{% endblock %}</title>
	</head>
	<body>
        {% block content %}{% endblock %}
	</body>
</html>

Project-Online-Doctor-devel/POD/SDDDS/templates/SDDDS/results.html
{% extends "SDDDS/base.html" %}

{% block title %}Doctors{% endblock %}

{% block content %}
		<h1>Специалисты:</h1>
		<ul>
		{% for doc in doctors %}
			<li><label class="doctors">{{ doc }}</label></li>
		{% endfor %}
		</ul>
{% endblock %}

Project-Online-Doctor-devel/POD/SDDDS/templates/SDDDS/symptoms.html
{% extends "SDDDS/base.html" %}

{% block title %}Symptoms{% endblock %}

{% block content %}
		<h1>Выбор симптомов</h1>

		<form action="{% url 'sddds:process_symptoms' %}" method="post">

			{% csrf_token %}
			<div class="scategories-block">
				{% for i in categories %}
					<details class="scategory">
						<summary class="h4">{{ i.category_name }}:</summary>
						<ul>
							{% for j in i.symptom_set.all %}
								<li>
										<input type="checkbox" name="slist" id="{{ i.category_name }}symptom{{ forloop.counter }}" value="{{ j }}">
										<label for="{{ i.category_name }}symptom{{ forloop.counter }}">{{ j }}</label>
								</li>
							{% endfor %}
						</ul>
					</details>
				{% endfor %}
			</div>
			<input type="submit" class="otprbtn" value="Отправить">

		</form>
		
{% endblock %}